name: Deploy to Windows Server

on:
  push:
    branches:
      - main  # El flujo de trabajo se ejecutará cuando se haga push a la rama 'main'

jobs:
  deploy:
    runs-on: windows-latest  # Ejecutar el trabajo en un entorno de Windows

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Este paso toma el código de tu repositorio

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.5  # Usar la acción SSH para conectarse al servidor Windows
        with:
          host: ${{ secrets.WINDOWS_SERVER_IP }}  # IP del servidor Windows, se toma desde los secretos
          username: ${{ secrets.WINDOWS_SERVER_USER }}  # Nombre de usuario del servidor Windows
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # La clave privada SSH para autenticación

      - name: Deploy API to Windows Server
        run: |
          ssh ${{ secrets.WINDOWS_SERVER_USER }}@${{ secrets.WINDOWS_SERVER_IP }} << EOF
            cd C:/path/to/your/api  # Cambia la ruta a tu carpeta de la API
            git pull origin main  # Hacer pull de los últimos cambios del repositorio
            dotnet publish --configuration Release --output C:/path/to/your/api/out  # Publicar la aplicación
            net stop "ApiServiceName"  # Detener el servicio si está en ejecución (opcional)
            net start "ApiServiceName"  # Iniciar el servicio de nuevo
          EOF

      - name: Deploy MVC to Windows Server
        run: |
          ssh ${{ secrets.WINDOWS_SERVER_USER }}@${{ secrets.WINDOWS_SERVER_IP }} << EOF
            cd C:/path/to/your/mvc  # Cambia la ruta a tu carpeta de la MVC
            git pull origin main  # Hacer pull de los últimos cambios del repositorio
            dotnet publish --configuration Release --output C:/path/to/your/mvc/out  # Publicar la aplicación
            net stop "MvcServiceName"  # Detener el servicio si está en ejecución (opcional)
            net start "MvcServiceName"  # Iniciar el servicio de nuevo
          EOF
